// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdersApi.Data;

#nullable disable

namespace OrdersApi.Migrations
{
    [DbContext(typeof(RetailDbContext))]
    partial class RetailDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrdersApi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Seattle",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            State = "WA"
                        },
                        new
                        {
                            Id = 2,
                            City = "Portland",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@example.com",
                            FirstName = "Bob",
                            LastName = "Smith",
                            State = "OR"
                        },
                        new
                        {
                            Id = 3,
                            City = "San Francisco",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol@example.com",
                            FirstName = "Carol",
                            LastName = "Williams",
                            State = "CA"
                        },
                        new
                        {
                            Id = 4,
                            City = "Denver",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "david@example.com",
                            FirstName = "David",
                            LastName = "Brown",
                            State = "CO"
                        },
                        new
                        {
                            Id = 5,
                            City = "Austin",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "eva@example.com",
                            FirstName = "Eva",
                            LastName = "Davis",
                            State = "TX"
                        });
                });

            modelBuilder.Entity("OrdersApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OrdersApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OrdersApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mechanical Keyboard",
                            Price = 89.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 3,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "USB-C Hub",
                            Price = 49.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Webcam HD",
                            Price = 59.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 11,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "27\" 4K Monitor",
                            Price = 349.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 12,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Portable SSD 1TB",
                            Price = 89.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 13,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wireless Charger Pad",
                            Price = 19.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 14,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "HDMI Cable 6ft",
                            Price = 9.99m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 15,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "USB Flash Drive 64GB",
                            Price = 12.99m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 16,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart Power Strip",
                            Price = 34.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 17,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tablet Stand",
                            Price = 24.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 18,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop Docking Station",
                            Price = 149.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 19,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ethernet Adapter USB-C",
                            Price = 18.99m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 20,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wireless Presenter Remote",
                            Price = 29.99m,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 21,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Surge Protector 8-Outlet",
                            Price = 22.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 22,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "MicroSD Card 128GB",
                            Price = 17.99m,
                            StockQuantity = 350
                        },
                        new
                        {
                            Id = 23,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Portable Monitor 15.6\"",
                            Price = 199.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 24,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cable Management Kit",
                            Price = 14.99m,
                            StockQuantity = 270
                        },
                        new
                        {
                            Id = 25,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart Plug 4-Pack",
                            Price = 29.99m,
                            StockQuantity = 160
                        },
                        new
                        {
                            Id = 26,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "USB Microphone",
                            Price = 69.99m,
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 8,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Noise-Cancelling Headphones",
                            Price = 199.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 9,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bluetooth Speaker",
                            Price = 34.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 27,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wireless Earbuds",
                            Price = 79.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 28,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Studio Monitor Speakers",
                            Price = 249.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 29,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Soundbar 2.1",
                            Price = 159.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 30,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Podcast Starter Kit",
                            Price = 129.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 31,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Audio Interface USB",
                            Price = 99.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 32,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "In-Ear Monitors",
                            Price = 59.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 33,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Turntable Bluetooth",
                            Price = 139.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 34,
                            Category = "Audio",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DAC/Amp Combo",
                            Price = 89.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 10,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ergonomic Chair Cushion",
                            Price = 44.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 35,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Standing Desk Converter",
                            Price = 279.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 36,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Whiteboard 36x24",
                            Price = 39.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 37,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desk Organizer Set",
                            Price = 24.99m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 38,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Filing Cabinet 3-Drawer",
                            Price = 119.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 39,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Paper Shredder",
                            Price = 59.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 40,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Label Maker",
                            Price = 29.99m,
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 41,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desk Calendar 2026",
                            Price = 12.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 42,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Ergonomic Footrest",
                            Price = 49.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 43,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitor Arm Mount",
                            Price = 89.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 44,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Noise Machine White",
                            Price = 34.99m,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 45,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bookshelf Desktop",
                            Price = 54.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 46,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Printer Paper 5-Ream",
                            Price = 27.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 47,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Sticky Notes Bulk Pack",
                            Price = 8.99m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 48,
                            Category = "Office",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Dry-Erase Markers 12pk",
                            Price = 11.99m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 4,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Monitor Stand",
                            Price = 39.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 5,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desk Lamp",
                            Price = 24.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 7,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop Sleeve",
                            Price = 19.99m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 49,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop Backpack",
                            Price = 59.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 50,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mouse Pad XL",
                            Price = 14.99m,
                            StockQuantity = 300
                        },
                        new
                        {
                            Id = 51,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Wrist Rest Keyboard",
                            Price = 16.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 52,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Screen Cleaning Kit",
                            Price = 9.99m,
                            StockQuantity = 350
                        },
                        new
                        {
                            Id = 53,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Phone Stand Adjustable",
                            Price = 12.99m,
                            StockQuantity = 280
                        },
                        new
                        {
                            Id = 54,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Keyboard Cover",
                            Price = 7.99m,
                            StockQuantity = 400
                        },
                        new
                        {
                            Id = 55,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Privacy Screen Filter",
                            Price = 34.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 56,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Webcam Cover 6-Pack",
                            Price = 5.99m,
                            StockQuantity = 600
                        },
                        new
                        {
                            Id = 57,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cable Clips 20-Pack",
                            Price = 6.99m,
                            StockQuantity = 500
                        },
                        new
                        {
                            Id = 58,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Laptop Cooling Pad",
                            Price = 29.99m,
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 59,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Headphone Stand",
                            Price = 19.99m,
                            StockQuantity = 170
                        },
                        new
                        {
                            Id = 60,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Travel Tech Pouch",
                            Price = 22.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 61,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Smart Water Bottle",
                            Price = 34.99m,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 62,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Yoga Mat Premium",
                            Price = 39.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 63,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Resistance Bands Set",
                            Price = 19.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 64,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fitness Tracker Band",
                            Price = 49.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 65,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Foam Roller",
                            Price = 24.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 66,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Jump Rope Speed",
                            Price = 12.99m,
                            StockQuantity = 250
                        },
                        new
                        {
                            Id = 67,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Massage Gun Mini",
                            Price = 89.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 68,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Balance Board",
                            Price = 44.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 69,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Posture Corrector",
                            Price = 29.99m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 70,
                            Category = "Fitness & Wellness",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Blue Light Glasses",
                            Price = 24.99m,
                            StockQuantity = 220
                        },
                        new
                        {
                            Id = 71,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Insulated Travel Mug",
                            Price = 24.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 72,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pour-Over Coffee Set",
                            Price = 34.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 73,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Electric Kettle",
                            Price = 44.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 74,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Desk Snack Container Set",
                            Price = 16.99m,
                            StockQuantity = 170
                        },
                        new
                        {
                            Id = 75,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "French Press 34oz",
                            Price = 29.99m,
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 76,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Reusable Straw Set",
                            Price = 8.99m,
                            StockQuantity = 350
                        },
                        new
                        {
                            Id = 77,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Lunch Box Bento",
                            Price = 19.99m,
                            StockQuantity = 140
                        },
                        new
                        {
                            Id = 78,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cold Brew Maker",
                            Price = 27.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 79,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tea Infuser Bottle",
                            Price = 15.99m,
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 80,
                            Category = "Kitchen & Drinkware",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Espresso Cups Set of 4",
                            Price = 22.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 81,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Clean Code Book",
                            Price = 39.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 82,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "System Design Interview",
                            Price = 35.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 83,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cloud Architecture Patterns",
                            Price = 44.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 84,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Data Science Handbook",
                            Price = 49.99m,
                            StockQuantity = 35
                        },
                        new
                        {
                            Id = 85,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "DevOps Handbook",
                            Price = 34.99m,
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 86,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Kubernetes Up & Running",
                            Price = 42.99m,
                            StockQuantity = 45
                        },
                        new
                        {
                            Id = 87,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Learning SQL",
                            Price = 29.99m,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 88,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Designing Data Apps",
                            Price = 47.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 89,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "The Pragmatic Programmer",
                            Price = 41.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 90,
                            Category = "Books & Learning",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Site Reliability Engineering",
                            Price = 38.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 91,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gaming Mouse RGB",
                            Price = 49.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 92,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mechanical Gaming Keyboard",
                            Price = 119.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 93,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Controller Wireless",
                            Price = 59.99m,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 94,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gaming Headset 7.1",
                            Price = 79.99m,
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 95,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Mouse Bungee",
                            Price = 14.99m,
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 96,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Stream Deck Mini",
                            Price = 79.99m,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 97,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Gaming Desk Mat XXL",
                            Price = 29.99m,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 98,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Capture Card HD",
                            Price = 129.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 99,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "VR Headset Stand",
                            Price = 24.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 100,
                            Category = "Gaming",
                            CreatedAt = new DateTime(2016, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "LED Light Strip RGB 10ft",
                            Price = 18.99m,
                            StockQuantity = 250
                        });
                });

            modelBuilder.Entity("OrdersApi.Models.Order", b =>
                {
                    b.HasOne("OrdersApi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OrdersApi.Models.OrderItem", b =>
                {
                    b.HasOne("OrdersApi.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrdersApi.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OrdersApi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
